# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - restore_cache:
          keys: pip-cache

      - run:
          name: install dependencies
          command: |
            if [ ! -x venv ]; then
              python3 -m venv venv
            fi
            . venv/bin/activate
            pip config set global.progress_bar off
            pip install -r requirements-dev.txt
            pip install -e .
            pip install codecov

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - save_cache:
          key: pip-cache
          paths:
          - "~/.cache/pip"

      - run:
          name: make lint
          command: |
            . venv/bin/activate
            make lint

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -v tests/ -n 3 --cov=src --cov-report=xml --junitxml=test-reports/junit.xml
            codecov

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
