from datetime import timedelta

DEFAULT_REQUIRED_CONFIRMATIONS: int = 10
MAX_FILTER_INTERVAL: int = 100_000
DEFAULT_GAS_BUFFER_FACTOR: int = 10
DEFAULT_GAS_CHECK_BLOCKS: int = 100
DEFAULT_PAYMENT_RISK_FAKTOR: int = 2
KEEP_MRS_WITHOUT_CHANNEL: timedelta = timedelta(minutes=15)

MATRIX_RATE_LIMIT_ALLOWED_BYTES = 5_000_000
MATRIX_RATE_LIMIT_RESET_INTERVAL = timedelta(minutes=5)
