version: '3.4'

x-defaults: &defaults
  image: raiden-services
  env_file: .env
  volumes:
    - ${DATA_DIR:-./data}/state:/state
    - ${DATA_DIR:-./data}/keystore:/keystore

services:
  pfs:
    << : *defaults
    command: ["python3", "-m", "pathfinding_service.cli"]
    restart: always
    ports:
      - 6001:6000
    environment:
      - PFS_KEYSTORE_FILE=${SERVER_NAME}
      - PFS_STATE_DB=/state/pfs-state.db
      - PFS_HOST=0.0.0.0
      - SERVER_NAME
      - PFS_LOG_LEVEL=${LOG_LEVEL}
      - PFS_KEYSTORE_FILE=/keystore/${KEYSTORE_FILE}
      - PFS_PASSWORD=${PASSWORD}
      - PFS_ETH_RPC=${ETH_RPC}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${SERVER_NAME}"

  ms:
    << : *defaults
    command: ["python3", "-m", "monitoring_service.cli"]
    restart: always
    ports:
      - 6002:6000
    environment:
      - MS_STATE_DB=/state/ms-state.db
      - MS_LOG_LEVEL=${LOG_LEVEL}
      - MS_KEYSTORE_FILE=/keystore/${KEYSTORE_FILE}
      - MS_PASSWORD=${PASSWORD}
      - MS_ETH_RPC=${ETH_RPC}

  msrc:
    << : *defaults
    command: ["python3", "-m", "request_collector.cli"]
    restart: always
    ports:
      - 6003:6000
    environment:
      - MSRC_STATE_DB=/state/ms-state.db
      - MSRC_LOG_LEVEL=${LOG_LEVEL}
      - MSRC_KEYSTORE_FILE=/keystore/${KEYSTORE_FILE}
      - MSRC_PASSWORD=${PASSWORD}
      - MSRC_CHAIN_ID=${CHAIN_ID}
    depends_on:
      - ms

  traefik:
    image: traefik:1.7
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/traefik:/etc/traefik
      - ${DATA_DIR:-./data}/traefik:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: --acme.email=${LETSENCRYPT_EMAIL}
    depends_on:
      - pfs
      - ms
      - msrc

  # This registers the service and stops afterwards
  registration:
    <<: *defaults
    command: ["python3", "-m", "raiden_libs.register_service"]
    environment:
      - RDN_REGISTRY_LOG_LEVEL=${LOG_LEVEL}
      - RDN_REGISTRY_KEYSTORE_FILE=/keystore/${KEYSTORE_FILE}
      - RDN_REGISTRY_PASSWORD=${PASSWORD}
      - RDN_REGISTRY_DEPOSIT=${RDN_DEPOSIT}
      - RDN_REGISTRY_SERVICE_URL=${SERVER_NAME}
    depends_on:
      - traefik
